### ISSUE TITLE
关于词向量的问题

### ISSUE THREAD

**Issue by MiniBullLab** [qhduan/Seq2Seq_Chatbot_QA#1]
我有一个问题，这里面的词向量你是如何做的，在EmbeddingWrapper里面没有输入input，没有得到每个字的词向量，并且在rnn.rnn中的encoder_inputs是一个二维的，列是batch_size，行是bucket。那怎么表示词向量呢？

**Comment by qhduan** [comment]
我没有做词向量
输入的就是词在字典的index
词向量是tf.nn.seq2seq.embedding_attention_seq2seq这个自动做了
内部机制应该是一种random embedding

**Comment by qhduan** [comment]
@wfw11223344 不知道我说明白了吗？如果有想讨论的可以再说～～
