### ISSUE TITLE
 import s2s.data_util as data_util

### ISSUE THREAD

**Issue by wangejay** [qhduan/Seq2Seq_Chatbot_QA#2]
$ python3 train.py
train.py can't import data_util

請問我沒有 data_util lib, 這要如何安裝呢?  查了網路上並找不到相關的答案，想要問你是否知道呢?

**Comment by qhduan** [comment]
data_util就是项目下面的data_util.py文件呀

之前有一段时间项目里面的train.py的代码是有问题的，现在应该没问题了，请尝试git pull更新之后再试一下

**Comment by qhduan** [comment]
@wangejay 您好，我更新了一些代码，改变比较大，主要加入了buckets机制

我尽量把readme写的清晰一点吧，其实代码也不难懂啦，官方的translate代码改而已

希望能帮到你
