### ISSUE TITLE
执行s2s时报错

### ISSUE THREAD

**Issue by xiyanxiyan10** [qhduan/Seq2Seq_Chatbot_QA#24]
InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./model/model1/model: Not found: ./model/model1; No such file or directory

**Comment by qhduan** [comment]
#21

参考下这个？

可以手动修改代码里面的模型路径

**Comment by xiyanxiyan10** [comment]
已解决
