### ISSUE TITLE
测试没有达到楼主的效果。。。。

### ISSUE THREAD

**Issue by wall-e-xusa** [qhduan/Seq2Seq_Chatbot_QA#4]
参数按照楼主的设置，迭代样本为1000000次，效果不是很好，问：你好，回答不是你好，loss最终0.769，看了训练语料发现对白分割并不严格。。。达到楼主的效果参数是怎样的？

**Comment by qhduan** [comment]
我的效果也不好，readme列的是某一次，我都不记得什么参数了的效果，我自己都没有那个模型了

这个其实也不是loss越低越好……甚至也不是bleu越高越好，对话效果是比较主观的

总体来说，不要太期待，娱乐向就好了

如果能随便做一下就达到图灵机器人的水平，那人家也不用活了～～～

如果你对此类机器人平台感兴趣可以看看我的调研

https://github.com/qhduan/ConversationalRobotDesign/blob/master/%E5%90%84%E7%A7%8D%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%B9%B3%E5%8F%B0%E8%B0%83%E7%A0%94.md

**Comment by qhduan** [comment]
要“效果”比较好，我觉得可以根据需求，把语聊分的很细，例如“吸血鬼小说、电影”，然后专门针对这个，训练到过拟合，有很多这个分类，然后可能会有点意思。

那个对白分割不是我分的呀，你可以看原repo，不过那个确实是不好，我自己也分过，做不到很好啊，如果你有好的建议欢迎～～～

当然如果有更好的语聊就好了，例如一大堆格式比较好的剧本

A君：你好
B君：23333

这样的，当然更好了，不过这种数据本就很少～～

**Comment by wall-e-xusa** [comment]
谢谢分享了，我也正在学习之中
